# -*- coding: utf-8 -*-
"""tarea control 03/10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqW7FUGXnAr8-pkzYdJZy4PiPtsBIcKe
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 10, 100)
y = 2 * x + np.random.randn(100)
plt.plot(x, 2 * x, label='Línea (2x)')
plt.scatter(x, y, color='red', label='Dispersión (2x + ruido)')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()